# Generated by Django 5.1.4 on 2025-03-10 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_push_cloud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='url',
        ),
    ]
